CREATE TABLE TASK (id BIGINT NOT NULL, DESCRIPTION VARCHAR(2000) NOT NULL, FINISHED SMALLINT DEFAULT 0, task_name VARCHAR(255) NOT NULL, version INTEGER, PRIMARY KEY (id))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
